# ─────────────────────────────────────────────
#  CDY2204 - Sistema de Inscripción de Cursos
#  Configuración Oracle Cloud
# ─────────────────────────────────────────────

spring.application.name=sistema-inscripcion
server.port=8080

# Oracle Cloud - reemplaza con tus credenciales
spring.datasource.url=jdbc:oracle:thin:@<TU_HOST>:1521/<TU_SERVICE>
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Respuestas JSON en español
spring.jackson.serialization.indent-output=true
